### ISSUE TITLE
Rotating the board as a method for movements

### ISSUE THREAD

**Issue by modicohen** [Yeedle/2048#3]
It makes the code much clearer and less complicated. However, it might be too heavy for smooth processing since every movement besides 'left' will cause the board to rotate 4 times. It is something that we will have to test. What say you, @Yeedle ?

**Comment by yeedle** [comment]
@modicohen Why does rotating the board make for clearer code?

**Comment by modicohen** [comment]
For example, translating the move from left to down will be super messy...

**Comment by yeedle** [comment]
I think a more accurate representation of the board would be to pass a direction as a parameter to the shiftBoard method. You can perhaps implement the calculations internally in the logic class (which is currently implemented in the BoardFun class) by treating everything as a left move and then translate it by rotating the board according to the direction of the move, but ultimately when the results are returned, the GUI class should only get the information about which Tiles have to be merged.

**Comment by modicohen** [comment]
This issue is resolved. Although there is a way to reduce the constant of O(n), since in any case the complexity will stay n.
