### ISSUE TITLE
Values after shifts are incorrect

### ISSUE THREAD

**Issue by modicohen** [Yeedle/2048#4]
As @Yeedle noticed, my current algorithm doesn't provide the correct values for tiles that were moved via the shiftZeros() method. The core of the issue is that in order for my mergeRow() algorithms to work I implemented shiftZeros() so that it swaps the actual tile on the grid and not just the value. The problem is, since it only swaps the reference to the tile, the tiles are not actually swaped from the GUI's perspective.

To address this issue, I decided that the most straight-forward, efficient approach would be to code an algorithm that would shift and merge tiles in one pass. Although it will increase the code's complexity, it will be the simplest (and most efficient) approach to allow values to be merged and shifted between tiles while marking the correct transition values in the original tile.

What do you think, @Yeedle?

**Comment by yeedle** [comment]
@modicohen Can you elaborate a but more on what "shift and merge the board in one pass" entails? If you don't mean shifting the tiles in the army but swapping the values, I think that will work.

**Comment by modicohen** [comment]
> Can you elaborate a but more on what "shift and merge the board in one pass" entails?

What it means is that I will have one loop that will do all the work in 1 pass.

>  If you don't mean shifting the tiles in the army but swapping the values

In my new algorithm, values are swapped between tiles while the the correct transition values are set in the original tile.

> I think that will work.

I think so too.

**Comment by yeedle** [comment]
@modicohen Sounds good

**Comment by modicohen** [comment]
@Yeedle looks good too
